---
formatter: markdown table
sort:
  by: required

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    <!-- prettier-ignore-start -->

    {{ .Content }}

    <!-- prettier-ignore-end -->
    <!-- END_TF_DOCS -->
